### ISSUE TITLE
DrawState layer: Invalid "srcStageMask in vkCmdWaitEvents must be the bitwise OR of the stageMask parameters used in calls to vkCmdSetEvent" error reported

### ISSUE THREAD

**Issue by DominikWitczakAMD** [KhronosGroup/Vulkan-LoaderAndValidationLayers#104]
In my scenario, the masks actually match.

The problem is incorrectly reported by the DS layer if vkCmdWaitEvents() is recorded in a command buffer, which is different from the one which holds the corresponding vkCmdSetEvent() call. This is perfectly fine, as per spec language, as long as vkCmdSetEvent() precedes the vkCmdWaitEvents() call, and assuming correct command buffer synchronization.

Having had a brief look at how vkCmdWaitEvents() is implemented in draw_state.cpp, it seems like the event stage mask is kept in a command buffer node, which would explain why I'm seeing this call-back.

**Comment by lentinem** [comment]
I'll take a brief look to see if something is obvious here. The way the set/wait tracking works is that there are two states: one in commandbuffer and one outside of it which are both checked.

**Comment by DominikWitczakAMD** [comment]
Continues to reproduce with one of the apps I have. Let me know if you need further details on how to repro this.

**Comment by lentinem** [comment]
Yes this is fixed in a change that hasn't been merged yet and should still be an issue. I'll update when it's been committed.

**Comment by lentinem** [comment]
This should be committed now.

**Comment by DominikWitczakAMD** [comment]
Continues to reproduce. However, having had a look, I believe the reason I'm still seeing this is because of #212.

**Comment by lentinem** [comment]
After the 212 fixed has been merged it would be good to check this again.

**Comment by DominikWitczakAMD** [comment]
The good news I have is that the use case described in this ticket no longer reproduces the described problem. The bad news :) is that I found another way to get Core Validation to produce this call-back incorrectly. In order to avoid confusion,  I'm going to open a separate ticket for the other use case.

**Comment by DominikWitczakAMD** [comment]
#241 describes the other use case in more detail.
