### ISSUE TITLE
wierd problem when try build 32 bits of Vulkan-LoaderAndValidationLayers

### ISSUE THREAD

**Issue by sl1pkn07** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1110]
if set:

```
  export CC='gcc -m32'
  export CXX='g++ -m32'
  export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
```

Vulkan-LoaderAndValidationLayers cmakecache.txt found 64 bits libs instead of 32bits

example:
![](http://wstaw.org/m/2016/10/28/Screenshot_20161028_171841.png)

full cmakecache.txt https://sl1pkn07.wtf/paste/view/2eefbc07

full cmake opts:

```
  export CC='gcc -m32'
  export CXX='g++ -m32'
  export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
cmake ../Vulkan-LoaderAndValidationLayers \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DCMAKE_INSTALL_LIBDIR=lib32 \
    -DCMAKE_INSTALL_SYSCONFDIR=/etc \
    -DCMAKE_SKIP_RPATH=ON \
    -DBUILD_DEMOS=ON \
    -DBUILD_TESTS=OFF \
    -DBUILD_WSI_WAYLAND_SUPPORT=ON \
    -DGLSLANG_LIB="${srcdir}/fakeroot/usr/lib32/libglslang.a" \
    -DGLSLANG_VALIDATOR="${srcdir}/fakeroot/usr/bin/glslangValidator" \
    -DGLSLANG_BINARY_ROOT="${srcdir}/fakeroot/usr/bin" \
    -DOGLCompiler_LIB="${srcdir}/fakeroot/usr/lib32/libOGLCompiler.a" \
    -DOSDependent_LIB="${srcdir}/fakeroot/usr/lib32/libOSDependent.a" \
    -DSPIRV_LIB="${srcdir}/fakeroot/usr/lib32/libSPIRV.a" \
    -DSPIRV_REMAPPER_LIB="${srcdir}/fakeroot/usr/lib32/libSPVRemapper.a" \
    -DSPIRV_TOOLS_LIB="${srcdir}/fakeroot/usr/lib32/libSPIRV-Tools.a" \
    -DSPIRV_TOOLS_INCLUDE_DIR="${srcdir}/fakeroot/usr/include" \
    -DSPIRV_TOOLS_BINARY_ROOT="${srcdir}/fakeroot/usr/bin" \
    -DHLSL_LIB="${srcdir}/fakeroot/usr/lib32/libHLSL.a" \
    -DCUSTOM_GLSLANG_BIN_ROOT=ON \
    -DCUSTOM_SPIRV_TOOLS_BIN_ROOT=ON
  make
```

all needed lib32 bits libs already installed

greetings

**Comment by karl-lunarg** [comment]
Can you please be more specific about what is actually going wrong?  For example, which 64-bit libs are getting found instead of their 32-bit versions?  The included example doesn't give enough information that is actionable.

Is this a regression?  If this used to work, please specify the last working commit.

This isn't an item that is high priority for us, but we'd like to be able to help fix it.  So, more info and help would be appreciated.

**Comment by sl1pkn07** [comment]
sorry. the paste is out

https://www.dropbox.com/s/b0akx6lpoo4mxu7/2eefbc07.txt?dl=0

**Comment by karl-lunarg** [comment]
Sorry, still not enough.  Can you try answering my questions?

**Comment by sl1pkn07** [comment]
X11_ICE_LIB:FILEPATH=/usr/lib/libICE.so
X11_SM_LIB:FILEPATH=/usr/lib/libSM.so
X11_X11_LIB:FILEPATH=/usr/lib/libX11.so
X11_XRes_LIB:FILEPATH=/usr/lib/libXRes.so
X11_XTest_LIB:FILEPATH=/usr/lib/libXtst.so
X11_Xau_LIB:FILEPATH=/usr/lib/libXau.so
X11_Xcomposite_LIB:FILEPATH=/usr/lib/libXcomposite.so
X11_Xcursor_LIB:FILEPATH=/usr/lib/libXcursor.so
X11_Xdamage_LIB:FILEPATH=/usr/lib/libXdamage.so
X11_Xdmcp_LIB:FILEPATH=/usr/lib/libXdmcp.so
X11_Xext_LIB:FILEPATH=/usr/lib/libXext.so
X11_Xfixes_LIB:FILEPATH=/usr/lib/libXfixes.so
X11_Xft_LIB:FILEPATH=/usr/lib/libXft.so
X11_Xi_LIB:FILEPATH=/usr/lib/libXi.so
X11_Xinerama_LIB:FILEPATH=/usr/lib/libXinerama.so
X11_Xinput_LIB:FILEPATH=/usr/lib/libXi.so
X11_Xkbfile_LIB:FILEPATH=/usr/lib/libxkbfile.so
X11_Xmu_LIB:FILEPATH=/usr/lib/libXmu.so
X11_Xpm_LIB:FILEPATH=/usr/lib/libXpm.so
X11_Xrandr_LIB:FILEPATH=/usr/lib/libXrandr.so
X11_Xrender_LIB:FILEPATH=/usr/lib/libXrender.so
X11_Xscreensaver_LIB:FILEPATH=/usr/lib/libXss.so
X11_Xt_LIB:FILEPATH=/usr/lib/libXt.so
X11_Xv_LIB:FILEPATH=/usr/lib/libXv.so
X11_Xxf86misc_LIB:FILEPATH=/usr/lib/libXxf86misc.so
X11_Xxf86vm_LIB:FILEPATH=/usr/lib/libXxf86vm.so
XCB_LIBRARY:FILEPATH=/usr/lib/libxcb.so
 

the path should be /usr/lib32

like

WAYLAND_CLIENT_LIBRARIES:FILEPATH=/usr/lib32/libwayland-client.so
WAYLAND_CURSOR_LIBRARIES:FILEPATH=/usr/lib32/libwayland-cursor.so
WAYLAND_EGL_LIBRARIES:FILEPATH=/usr/lib32/libwayland-egl.so
WAYLAND_SERVER_LIBRARIES:FILEPATH=/usr/lib32/libwayland-server.so

**Comment by karl-lunarg** [comment]
Thanks for the extra info.

I got this to work:

`CFLAGS=-m32 CXXFLAGS=-m32 PKG_CONFIG_LIBDIR=/usr/lib/i386-linux-gnu cmake -H. -Bbuild -DBUILD_TESTS=NO -DBUILD_LAYERS=NO`

After I do this, I see in the CMakeCache.txt:

```
//Path to a library.
X11_X11_LIB:FILEPATH=/usr/lib/i386-linux-gnu/libX11.so

```

instead of the 

```
//Path to a library.
X11_X11_LIB:FILEPATH=/usr/lib/x86_64-linux-gnu/libX11.so

```

I think that CMake will do a better job at finding the right libraries if you set the C/CXX flags, instead of overriding the compiler name (CC and CXX).

Online searches seemed to suggest that just setting the -m32 flag as above should be enough, but doing just that made CMake generate linker directives to link the 64-bit XCB lib.  I had to add the PKG_CONFIG_LIBDIR to fix that.

But for me, using the unchanged LVL repo, I was able to build a working 32-bit vulkaninfo, cube, and smoketest.

There are a lot of compilation warnings in the loader when building 32-bit.  We'll have to look at those.

**Comment by karl-lunarg** [comment]
I'll leave this issue open and assigned to me, so that I can finish fixing any other issues with 32-bit support, including the compiler warnings in the loader.

LunarG never officially supported/tested this repo on 32-bit Linux, so this work is largely unplanned.

I'm assuming that the hints I gave above help get past the original problem.  Please advise if that is not the case.

**Comment by sl1pkn07** [comment]
nope here, 

with 
```
  export CC="gcc -m32"
  export CXX="g++ -m32"
  export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
  export PKG_CONFIG_LIBDIR="/usr/lib32"
```

or

```
  export CFLAGS="-m32"
  export CXXFLAGS="-m32"
  export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
  export PKG_CONFIG_LIBDIR="/usr/lib32"
```

have same output like the first and https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/issues/1110#issuecomment-257461667

the detection of wayland libs work ok (point to /usr/lib32), but not the rest of the libs

**Comment by karl-lunarg** [comment]
Did you completely clean up any cmake cache files, etc, between the two attempts?  That is, make sure cmake is starting from scratch, with the settings I used.  

Specifying CFLAGS and CXXFLAGS (or equivalently, -DCMAKE_C_FLAGS and -DCMAKE_CXX_FLAGS in the cmake invocation) should work, according to all I've seen online.

Since we're getting different results, you'll have to do some digging on your end to find the problem and suggest changes to improve things.  Maybe check the pkgconfig files in /usr/lib32?

**Comment by sl1pkn07** [comment]
yes. always use a clean directory in all build process, like `rm -fr build && mkdir -p build && cd build && cmake ../foo`

set -DCMAKE_C_FLAGS=-m32 and -DCMAKE_CXX_FLAGS=-m32 do nothing. same output

  export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
  export PKG_CONFIG_LIBDIR="/usr/lib32/pkgconfig"

also do nothing (both, or one, or other)

for the info, i use cmake 3.6.2

**Comment by karl-lunarg** [comment]
I pushed https://github.com/KhronosGroup/Vulkan-LoaderAndValidationLayers/pull/1177, which really just fixes some compiler warnings in the loader when compiling for 32-bit.  I also updated the docs to explain that 32-bit builds aren't really supported or tested on Linux, but should work OK due to the need to support 32-bit on other targets.

I'm using cmake 3.5.1 and it seems unlikely that a later version of cmake is causing the problem.

Since this is working OK for us on our "reference" Ubuntu platforms, I'll go ahead and close this.

If you can provide more info such as what distro you are using, etc, that would be helpful.  Even better would be if you can find out what is needed to fix the problem on your system and suggest a change that we can make.

**Comment by sl1pkn07** [comment]
unfortunately still have the problem. cmake found the 64bits libs paths instead of 32bits paths, the weird of this is only found the correct libs only the wayland libs, but not the rest.

my distribution is Archlinux

```
  -> Build Vulkan-LoaderAndValidationLayers
-- The C compiler identification is GNU 6.2.1
-- The CXX compiler identification is GNU 6.2.1
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found PythonInterp: /usr/bin/python3 (found suitable version "3.5.2", minimum required is "3") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Found xcb: /usr/include  
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - not found
-- Looking for dnet_ntoa in dnet
-- Looking for dnet_ntoa in dnet - not found
-- Looking for dnet_ntoa in dnet_stub
-- Looking for dnet_ntoa in dnet_stub - not found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/libX11.so
-- Found WAYLAND_CLIENT: /usr/lib32/libwayland-client.so  
-- Found WAYLAND_SERVER: /usr/lib32/libwayland-server.so  
-- Found WAYLAND_EGL: /usr/lib32/libwayland-egl.so  
-- Found WAYLAND_CURSOR: /usr/lib32/libwayland-cursor.so  
-- Found WAYLAND: /usr/lib32/libwayland-client.so;/usr/lib32/libwayland-server.so;/usr/lib32/libwayland-egl.so;/usr/lib32/libwayland-cursor.so  
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/makepkg/lib32-vulkan-git/src/build-vulkan-loaderandvalidationlayers
```

the cmakecache output is posted avobe. not chage

**Comment by sl1pkn07** [comment]
tested today again

the error is now fixed

now fould all 32bits libraries

```
X11_ICE_LIB:FILEPATH=/usr/lib32/libICE.so
X11_SM_LIB:FILEPATH=/usr/lib32/libSM.so
X11_X11_LIB:FILEPATH=/usr/lib32/libX11.so
X11_XRes_LIB:FILEPATH=/usr/lib32/libXRes.so
X11_XTest_LIB:FILEPATH=/usr/lib32/libXtst.so
X11_Xau_LIB:FILEPATH=/usr/lib32/libXau.so
X11_Xcomposite_LIB:FILEPATH=/usr/lib32/libXcomposite.so
X11_Xcursor_LIB:FILEPATH=/usr/lib32/libXcursor.so
X11_Xdamage_LIB:FILEPATH=/usr/lib32/libXdamage.so
X11_Xdmcp_LIB:FILEPATH=/usr/lib32/libXdmcp.so
X11_Xext_LIB:FILEPATH=/usr/lib32/libXext.so
X11_Xfixes_LIB:FILEPATH=/usr/lib32/libXfixes.so
X11_Xft_LIB:FILEPATH=/usr/lib32/libXft.so
X11_Xi_LIB:FILEPATH=/usr/lib32/libXi.so
X11_Xinerama_LIB:FILEPATH=/usr/lib32/libXinerama.so
X11_Xinput_LIB:FILEPATH=/usr/lib32/libXi.so
X11_Xkbfile_LIB:FILEPATH=/usr/lib32/libxkbfile.so
X11_Xmu_LIB:FILEPATH=/usr/lib32/libXmu.so
X11_Xpm_LIB:FILEPATH=/usr/lib32/libXpm.so
X11_Xrandr_LIB:FILEPATH=/usr/lib32/libXrandr.so
X11_Xrender_LIB:FILEPATH=/usr/lib32/libXrender.so
X11_Xscreensaver_LIB:FILEPATH=/usr/lib32/libXss.so
X11_Xt_LIB:FILEPATH=/usr/lib32/libXt.so
X11_Xv_LIB:FILEPATH=/usr/lib32/libXv.so
X11_Xxf86misc_LIB:FILEPATH=/usr/lib32/libXxf86misc.so
X11_Xxf86vm_LIB:FILEPATH=/usr/lib32/libXxf86vm.so
XCB_LIBRARY:FILEPATH=/usr/lib32/libxcb.so 
```

greetings
