### ISSUE TITLE
Loader checks for and advertises layers multiple times.

### ISSUE THREAD

**Issue by jekstrand** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1121]
When running the 1.0.1 CTS through the loader, dEQP-VK.api.info.instance.layers fails with "Duplicate layer: VK_LAYER_GOOGLE_threading".  The TestResults.qpa file provides a bit more detail:

> 0: VkLayerProperties = {
> 	layerName = VK_LAYER_LUNARG_core_validation
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = LunarG Validation Layer
> }
> 
> 1: VkLayerProperties = {
> 	layerName = VK_LAYER_LUNARG_image
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = LunarG Validation Layer
> }
> 
> 2: VkLayerProperties = {
> 	layerName = VK_LAYER_LUNARG_object_tracker
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = LunarG Validation Layer
> }
> 
> 3: VkLayerProperties = {
> 	layerName = VK_LAYER_LUNARG_parameter_validation
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = LunarG Validation Layer
> }
> 
> 4: VkLayerProperties = {
> 	layerName = VK_LAYER_LUNARG_swapchain
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = LunarG Validation Layer
> }
> 
> 5: VkLayerProperties = {
> 	layerName = VK_LAYER_GOOGLE_threading
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = Google Validation Layer
> }
> 
> 6: VkLayerProperties = {
> 	layerName = VK_LAYER_GOOGLE_unique_objects
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = Google Validation Layer
> }
> 
> 7: VkLayerProperties = {
> 	layerName = VK_LAYER_LUNARG_core_validation
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = LunarG Validation Layer
> }
> 
> 8: VkLayerProperties = {
> 	layerName = VK_LAYER_LUNARG_image
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = LunarG Validation Layer
> }
> 
> 9: VkLayerProperties = {
> 	layerName = VK_LAYER_LUNARG_object_tracker
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = LunarG Validation Layer
> }
> 
> 10: VkLayerProperties = {
> 	layerName = VK_LAYER_LUNARG_parameter_validation
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = LunarG Validation Layer
> }
> 
> 11: VkLayerProperties = {
> 	layerName = VK_LAYER_LUNARG_swapchain
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = LunarG Validation Layer
> }
> 
> 12: VkLayerProperties = {
> 	layerName = VK_LAYER_GOOGLE_threading
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = Google Validation Layer
> }
> 
> 13: VkLayerProperties = {
> 	layerName = VK_LAYER_GOOGLE_unique_objects
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = Google Validation Layer
> }
> 
> 14: VkLayerProperties = {
> 	layerName = VK_LAYER_VALVE_steam_overlay_32
> 	specVersion = 4194307
> 	implementationVersion = 1
> 	description = Steam Overlay Layer
> }
> 
> 15: VkLayerProperties = {
> 	layerName = VK_LAYER_VALVE_steam_overlay_64
> 	specVersion = 4194307
> 	implementationVersion = 1
> 	description = Steam Overlay Layer
> }
> 
> 16: VkLayerProperties = {
> 	layerName = VK_LAYER_RENDERDOC_Capture
> 	specVersion = 4194304
> 	implementationVersion = 30
> 	description = Debugging capture layer for RenderDoc
> }
> 
> 17: VkLayerProperties = {
> 	layerName = VK_LAYER_LUNARG_standard_validation
> 	specVersion = 4194334
> 	implementationVersion = 1
> 	description = LunarG Standard Validation Layer
> }

Running with VK_LOADER_DEBUG=all, I see the following:

> Searching the following paths for manifest files: /usr/etc/vulkan/explicit_layer.d:/usr/share/vulkan/explicit_layer.d:/etc/vulkan/explicit_layer.d:/usr/share/vulkan/explicit_layer.d
> 
> Searching the following path for manifest files: /home/jason/.local/share/vulkan/explicit_layer.d
> 
> Searching the following paths for manifest files: /usr/etc/vulkan/implicit_layer.d:/usr/share/vulkan/implicit_layer.d:/etc/vulkan/implicit_layer.d:/usr/share/vulkan/implicit_layer.d
> 
> Searching the following path for manifest files: /home/jason/.local/share/vulkan/implicit_layer.d
> 
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_core_validation.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_image.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_object_tracker.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_parameter_validation.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_swapchain.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_threading.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_unique_objects.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_core_validation.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_image.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_object_tracker.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_parameter_validation.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_swapchain.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_threading.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_unique_objects.json, version "1.0.0"
> Found manifest file /home/jason/.local/share/vulkan/implicit_layer.d/steamoverlay_i386.json, version "1.0.0"
> Found manifest file /home/jason/.local/share/vulkan/implicit_layer.d/steamoverlay_x86_64.json, version "1.0.0"
> Found manifest file /home/jason/.local/share/vulkan/implicit_layer.d/renderdoc_capture.json, version "1.0.0"
> Searching the following paths for manifest files: /usr/etc/vulkan/explicit_layer.d:/usr/share/vulkan/explicit_layer.d:/etc/vulkan/explicit_layer.d:/usr/share/vulkan/explicit_layer.d
> 
> Searching the following path for manifest files: /home/jason/.local/share/vulkan/explicit_layer.d
> 
> Searching the following paths for manifest files: /usr/etc/vulkan/implicit_layer.d:/usr/share/vulkan/implicit_layer.d:/etc/vulkan/implicit_layer.d:/usr/share/vulkan/implicit_layer.d
> 
> Searching the following path for manifest files: /home/jason/.local/share/vulkan/implicit_layer.d
> 
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_core_validation.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_image.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_object_tracker.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_parameter_validation.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_swapchain.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_threading.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_unique_objects.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_core_validation.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_image.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_object_tracker.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_parameter_validation.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_swapchain.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_threading.json, version "1.0.0"
> Found manifest file /usr/share/vulkan/explicit_layer.d/VkLayer_unique_objects.json, version "1.0.0"
> Found manifest file /home/jason/.local/share/vulkan/implicit_layer.d/steamoverlay_i386.json, version "1.0.0"
> Found manifest file /home/jason/.local/share/vulkan/implicit_layer.d/steamoverlay_x86_64.json, version "1.0.0"
> Found manifest file /home/jason/.local/share/vulkan/implicit_layer.d/renderdoc_capture.json, version "1.0.0"

It appears as if it's searching the directory twice.

**Comment by karl-lunarg** [comment]
Possibly fixed by #1084.

Hard to tell, because #1084 can happen only when CMAKE_INSTALL_PREFIX was used to build the repo.

**Comment by jekstrand** [comment]
In that case, it probably is #1084 because I'm using the distro-installed loader.  I'll build from git and see if I still have the problem.

**Comment by jekstrand** [comment]
That appears to be the issue.  I'll bother my distro people about shipping an update.
