### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by krOoze** [KhronosGroup/Vulkan-LoaderAndValidationLayers#1771]
I have a few tests that are failing on my platform:
Intel i5-3340, Windows 10 Pro N 1703 x64, AMD R9 280X 17.5.1

I build like this (from VS2017 developer prompt):

    update_external_sources.bat --all
    build_windows_targets.bat 64

When I run `build/tests/run_all_tests.ps1`:

1) I get only some 38 tests, not "all". Apparently only `vk_loader_validation_tests`

2) I get
```
[ RUN      ] Allocation.CreateInstanceDeviceItentionalAllocFail
C:\Dev\_GitHub\Vulkan-LoaderAndValidationLayers\tests\loader_validation_tests.cpp(1377): error: Value of: VK_SUCCESS
  Actual: 0
Expected: result
Which is: -3
[  FAILED  ] Allocation.CreateInstanceDeviceItentionalAllocFail (1368 ms)
```

When I run `VULKAN.sln` `vk_layer_validation_tests`:

3) I get (AKA VALIDATION_ERROR_14a004dc now) [fixed]
```
[ RUN      ] VkLayerTest.VALIDATION_ERROR_01412
Unexpected: Invalid Pipeline CreateInfo State: pColorBlendState is NULL when rasterization is enabled and subpass uses color attachments. For more information refer to Vulkan Spec Section '9.2. Graphics Pipelines' which states 'If the rasterizerDiscardEnable member of pRasterizationState is VK_FALSE, and subpass uses color attachments, pColorBlendState must be a pointer to a valid VkPipelineColorBlendStateCreateInfo structure' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkPipelineCreateFlagBits)
Unexpected: vkCreateGraphicsPipelines: pCreateInfo[0].pVertexInputState->vertexAttributeDescriptions[0].format (VK_FORMAT_UNDEFINED) is not a supported vertex buffer format. For more information refer to Vulkan Spec Section '20.2. Vertex Input Description' which states 'format must be allowed as a vertex buffer format, as specified by the VK_FORMAT_FEATURE_VERTEX_BUFFER_BIT flag in VkFormatProperties::bufferFeatures returned by vkGetPhysicalDeviceFormatProperties' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#VkVertexInputAttributeDescription)
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
ObjectTracker(ERROR): object: 0x9 type: 16 location: 383 msgCode: 49: OBJ ERROR : For device 0x111dd201020, ShaderModule object 0x9 has not been destroyed. For more information refer to Vulkan Spec Section '4.2.4. Device Destruction' which states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDestroyDevice)
ObjectTracker(ERROR): object: 0xa type: 16 location: 383 msgCode: 49: OBJ ERROR : For device 0x111dd201020, ShaderModule object 0xa has not been destroyed. For more information refer to Vulkan Spec Section '4.2.4. Device Destruction' which states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDestroyDevice)
ObjectTracker(ERROR): object: 0x8 type: 17 location: 383 msgCode: 49: OBJ ERROR : For device 0x111dd201020, PipelineCache object 0x8 has not been destroyed. For more information refer to Vulkan Spec Section '4.2.4. Device Destruction' which states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDestroyDevice)
ObjectTracker(ERROR): object: 0xb type: 18 location: 383 msgCode: 49: OBJ ERROR : For device 0x111dd201020, PipelineLayout object 0xb has not been destroyed. For more information refer to Vulkan Spec Section '4.2.4. Device Destruction' which states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDestroyDevice)
[  FAILED  ] VkLayerTest.VALIDATION_ERROR_01412 (333 ms)
```

4) And [no longer have this]
```
[ RUN      ] VkPositiveLayerTest.CreateComputePipelineCombinedImageSamplerConsumedAsBoth
unknown file: error: SEH exception with code 0xc0000005 thrown in the test body.
ObjectTracker(ERROR): object: 0x4 type: 16 location: 383 msgCode: 49: OBJ ERROR : For device 0x111e0fc6f50, ShaderModule object 0x4 has not been destroyed. For more information refer to Vulkan Spec Section '4.2.4. Device Destruction' which states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDestroyDevice)
ObjectTracker(ERROR): object: 0x3 type: 18 location: 383 msgCode: 49: OBJ ERROR : For device 0x111e0fc6f50, PipelineLayout object 0x3 has not been destroyed. For more information refer to Vulkan Spec Section '4.2.4. Device Destruction' which states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDestroyDevice)
ObjectTracker(ERROR): object: 0x2 type: 21 location: 383 msgCode: 49: OBJ ERROR : For device 0x111e0fc6f50, DescriptorSetLayout object 0x2 has not been destroyed. For more information refer to Vulkan Spec Section '4.2.4. Device Destruction' which states 'All child objects created on device must have been destroyed prior to destroying device' (https://www.khronos.org/registry/vulkan/specs/1.0-extensions/html/vkspec.html#vkDestroyDevice)
[  FAILED  ] VkPositiveLayerTest.CreateComputePipelineCombinedImageSamplerConsumedAsBoth (324 ms)
```

5) Some of the tests are skipped because this or that is unsupported. It would be nice if they could show "Inconclusive" in orange instead of "OK".

**Comment by mark-lunarg** [comment]
@MarkY-LunarG, I believe Jeremy is looking at the 01412 failure but you guys can have the other two.

**Comment by krOoze** [comment]
Nr. 4 possibly a driver bug? It crashes inside driver, and If I change
```
layout(set=0, binding=0) uniform texture2D t;
layout(set=0, binding=0) uniform sampler s;  // both binding 0!
```

to
```
layout(set=0, binding=0) uniform sampler2D s;
```

then it works fine.

I don't see anything wrong with the original. In spec 13.1.4. Combined Image Sampler the last paragraph seems to explicitly allow it.

**Comment by MarkY-LunarG** [comment]
Created a fix for the loader issues in #1792.  The layer issues are in another bug so once the PR passes the checks I'll commit can close this issue.

**Comment by MarkY-LunarG** [comment]
@krOoze, have you run your shader issue through SPIR-V validator?  I would open a new issue for this, and include a callstack to the failure.  We do very limited SPIR-V work in the layers (none in the loader) so it's likely a driver bug, but I can't say without more info.

**Comment by chrisforbes** [comment]
4 looks like a driver bug. The spec explicitly allows this.

Mark, we run the shader module through the validator at CreateShaderModule
time, so anything it can find should be reported by the layers.

**Comment by MarkY-LunarG** [comment]
Ok.  I just pushed a fix for the loader bug.  @mark-lunarg, was everything else covered by another issue?

**Comment by krOoze** [comment]
@MarkY-LunarG I still get nr. 2 even after that commit

> have you run your shader issue through SPIR-V validator?
yes, tried that also. It compiles, and the human readable form does look to me like some amalgamation of Sampler and Sampled Image examples from the spec.

**Comment by krOoze** [comment]
Nr. 2 possibly also driver bug.
The driver seems to return `VK_SUCCESS` with `count=0` from `vkEnumeratePhysicalDevices` when alloc inside it fails.

**Comment by cdwfs** [comment]
I just independently hit Nr. 3 (14a004dc) and I think I found the cause. The test tries to generate an invalid vertex attribute offset of limits.maxVertexInputAttributeOffset+1, but the AMD driver reports maxVertexInputAttributeOffset as 0xFFFFFFFF. It turns out zero is a perfectly valid offset :)

I'll submit a PR shortly that fixes that (and a couple other VU errors in that test that weren't being detected until the original error was accidentally skipped)

**Comment by cdwfs** [comment]
The fix for Nr. 3 is now in master (#1886 -- involved multiple VU errors and a driver bug, whee!)

**Comment by krOoze** [comment]
I no longer get # 4 with master and latest drivers.

**Comment by cdwfs** [comment]
Ah, great! I was just able to reproduce # 4 a couple days ago with the 17.4.4 Windows driver, but it looks like there was a new driver drop later that day that I missed. I'll confirm when I next have access to that system.

**Comment by cdwfs** [comment]
@krOoze: can you confirm that all the original issues you raised have been fixed? If not, it may be worth closing this issue and raising any remaining bugs as a new issue to avoid confusion.

**Comment by krOoze** [comment]
@cdwfs I still get nr. 2. Closing per your advice anyway.

**Comment by krOoze** [comment]
I am getting nr. 4 again for some time now.
It happens on `vkDestoryPipeline` (tries to destroy the combined sampler twice maybe?).
If I do not store the read in the shader the error disappears (the sampler and texture gets optimized away maybe?).
I'm just gonna report it as driver bug...

**Comment by cdwfs** [comment]
This repo has been deprecated, but for posterity: I also saw problem number 4 reappear as a brief driver regression (18.3.1), but it looks like it's fixed after updating to 18.4.1.
